config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'

  get '/auth/facebook/callback' => 'sessions#fbcreate'

  get 'login', to: 'sessions#new'
  get 'signup', to: 'accounts#new'
  get 'logout', to: 'sessions#destroy'
  post '/sessions/create', to: 'sessions#create'
  get '/most', to: 'holdings#most'

  resources :accounts
  
  resources :stocks do
    resources :holdings
  end

  resources :holdings

  

end

app/models/account.rb
class Account < ApplicationRecord
    has_secure_password
    validates :name, presence: { message: "Error: Name cannot be blank!" }
    validates :name, uniqueness: { message: "Error: Name is not available!" }
    #validates :password, length: {in: 4..100}

    has_many :holdings
    has_many :stocks, through: :holdings

    scope :investors, -> { where(broker_acc: false) }
    scope :vips, -> { investors.where("balance > 1000000") }

    def self.from_omniauth(auth)
        where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |acc|
            acc.provider = auth.provider
            acc.uid = auth.uid
            acc.name = auth.info.name unless acc.name != nil
            acc.password = SecureRandom.hex(10) unless acc.password != nil
            acc.save!
        end
    end
    
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/holding.rb
class Holding < ApplicationRecord
    belongs_to :account
    belongs_to :stock

    scope :most, -> { order(balance: :DESC).limit(1).first }

end

app/models/stock.rb
class Stock < ApplicationRecord
    has_many :holdings
    has_many :accounts, through: :holdings
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
    
    def index
        redirect_to login_path
    end

    def new
        if logged_in?
            redirect_to account_path(current_account)
        else
            @account = Account.new
        end
    end
    
    def create
        @account = Account.new(account_params)
        if @account.valid?
            @account.save
            #raise @account.inspect
            session[:acc_id] = @account.id
            redirect_to account_path(@account)
        else
            render 'new'
        end
    end

    def show
        if logged_in?
            @account = current_account
        else
            redirect_to login_path
        end
    end

    def update
        current_account.balance = params[:account][:balance]
        current_account.broker_acc = params[:account][:broker_acc]
        redirect_to account_path(@account)
    end

    def most
    end

    private

    def account_params
        params.require(:account).permit(:name, :password, :password_confirmation, :balance, :broker_acc)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_account, :logged_in?

    def current_account
        Account.find_by(id: session[:acc_id]) || nil
    end

    def logged_in?
        !!current_account
    end

end

app/controllers/holdings_controller.rb
require 'pry'

class HoldingsController < ApplicationController

    def new
        @holding = Holding.new(stock_id: params[:stock_id])
    end

    def create
        #raise params.inspect
        if logged_in? && params[:holding][:stock_id]
            @stock = Stock.find_by(id: params[:holding][:stock_id])
            cost = params[:holding][:balance].to_i * @stock.price
            if current_account.balance < cost
                flash[:alert] = "Sorry. You don't have enough balance"
                redirect_to stocks_path
            else
                if !params[:holding][:balance].empty?
                    total = current_account.balance - cost
                    @holding = Holding.create(holding_params)
                    @holding.account = current_account
                    @holding.stock = @stock 
                    current_account.update(balance: total)
                    @holding.price = @stock.price
                    @holding.save
                    @holding.account
                    if cost > 0
                        flash[:alert] = "You just bought #{@stock.name} stock"
                    else
                        flash[:alert] = "You just sold #{@stock.name} stock"
                    end
                    redirect_to stocks_path
                else
                    flash[:alert] = "Please input a valide number"
                    redirect_to stocks_path
                end
            end
        else
            redirect_to login_path
        end
    end

    def index
        if logged_in?
            @stock = Stock.find_by(id: params[:stock_id])
            @holdings = @stock.holdings.select { |f| f.account_id == current_account.id }
        else
            redirect_to login_path
        end
    end

    def show
        if logged_in? 
            @stock = Stock.find_by(id: params[:stock_id])
            @holding = Holding.find_by(id: params[:id])
            if @holding.account == current_account
                render 'show'
            else
                flash[:alert] = "Sorry. You don't have access to it"
                redirect_to login_path
            end
        else
            redirect_to login_path
        end
    end

    def update
        @stock = Stock.find_by(id: params[:holding][:stock_id])
        @holding = Holding.find_by(id: params[:id])
        if !params[:unit].empty? && params[:unit].to_i > 0 
            if params[:unit].to_i > @holding.balance
                flash[:alert] = "Sorry. You don't have enough balance"
                redirect_to stock_holding_path(@stock, @holding)
            else
                @holding.balance = @holding.balance - params[:unit].to_i
                @holding.save
                new_balance = params[:unit].to_i * @stock.price + current_account.balance
                current_account.update(balance: new_balance)
                redirect_to account_path(current_account)
            end
        else
            flash[:alert] = "Please enter a valid number"
            redirect_to stock_holding_path(@stock, @holding)
        end
    end

    private

    def holding_params
        params.require(:holding).permit(:account_id, :stock_id, :balance)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
    if !logged_in?
      @account = Account.new
    else
      flash[:alert] = "You already logged in."
      redirect_to account_path(current_account)
    end
  end

  def create
    @account = Account.find_by(name: params[:account][:name])
     if @account && @account.authenticate(params[:account][:password])
      session[:acc_id] = @account.id 
      redirect_to account_path(@account)
     else
      redirect_to login_path 
     end
  end

  def fbcreate
    @account = Account.from_omniauth(auth)
    session[:acc_id] = @account.id
    redirect_to account_path(@account)
  end

  def destroy
    session.delete :acc_id
    redirect_to login_path
  end

  private
 
  def auth
    request.env['omniauth.auth']
  end

end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
    
    def index
        @stocks = Stock.all
    end

    def new
        if logged_in? && current_account.broker_acc
            @stock = Stock.new
            render 'new'
        else
            flash[:alert] = "Sorry, you don't have access to it."
            redirect_to account_path(current_account)
        end
        
    end
    
    def create
        @stock = Stock.find_or_create_by(name: params[:stock][:name])
        @stock.update(stock_params)
        redirect_to stock_path(@stock)
    end

    def show
        @stock = Stock.find_by(id: params[:id])
    end

    def edit
        if logged_in? && current_account.broker_acc
            @stock = Stock.find_by(id: params[:id])
        else
            flash[:alert] = "Sorry, you don't have access to it."
            redirect_to stocks_path
        end
    end

    def update
        @stock = Stock.find_by(id: params[:id])
        @stock.update(stock_params)
        redirect_to stock_path(@stock)
    end

    private

    def stock_params
        params.require(:stock).permit(:name, :price)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

    
end

app/helpers/holdings_helper.rb
module HoldingsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/accounts/_alert.html.erb
<% if flash[:alert] %>
	<%= flash[:alert] %>
<% end %>

app/views/accounts/new.html.erb
<%= link_to "log In", login_path %><br>
<%= link_to('Log in with Facebook!', '/auth/facebook') %>
<br>
<br>
<% if @account.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@account.errors.count, "error") %>
      prohibited this account from being created:
    </h2>
    <ul>
    <% @account.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<br>
<br>
<%= form_for @account do |f| %>
    Username: <%= f.text_field :name %><br>
    Password: <%= f.password_field :password %><br>
    Password Confirmation: <%= f.password_field :password_confirmation %><br>
    $Balance: <%= f.text_field :balance %><br>
    Broker Account: <%= f.check_box :broker_acc %>
    <br>
    <br>
    <%= f.submit "Create Account" %>
   <% end %>
   
   

app/views/accounts/show.html.erb
<%= render 'alert' %>

<p>Name: <%= @account.name %></p>
<p>Balance: <%= @account.balance %></p>
<% if @account.broker_acc %>
<p>Broker Account: <%= "Yes" %></p>
<% end %>
<br>
Stock Portfolio:<br>
<table class="table">
  <thead>
    <tr>
      <th colspan="4"></th>
    </tr>
  </thead>
<tbody>
    <tr>
      <td><strong>Stock Name</strong></td>
      <td><strong>Balance</strong></td>
      <td><strong>Purchase Price</strong></td>
      <td><strong>Link</strong></td>
    </tr>
<% @account.holdings.each do |s| %>
  <% if s.balance > 0 %>
    <tr>
        <td><%= s.stock.name %></td>
        <td><%= s.balance %></td>
        <td><%= s.price %></td>
        <td><%= link_to "Sell #{s.stock.name}", stock_holding_path(s.stock, s) %></td>
    </tr>
  <%end%>
<% end %>
</tbody>
</table>
<br>
<br>

<% if @account.provider %>
<%= form_for @account do |f| %>
  Balance: <%= f.text_field :balance %><br>
  Broker Account: <%= f.check_box :broker_acc %>
  <br>
  <br>
  <%= f.submit "Enable Account" %>
 <% end %>
 <% end %>

 <%= link_to "Most Held Stock", '/most' %>
 <br>
 
<%= link_to "Stock Page", stocks_path %>
<br>
<%= link_to "Log Out", logout_path %>

app/views/holdings/index.html.erb
<h4>Stock: <%= @stock.name %></h4>

<br>
Stock Holding:<br>
<table class="table">
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>
<tbody>
    <tr>
      <td><strong>Purchase Price</strong></td>
      <td><strong>Amount</strong></td>
      <td><strong>Link</strong></td>
    </tr>
<% @holdings.each do |s| %>
    <tr>
        <td><%= s.price %></td>
        <td><%= s.balance %></td>
        <td><%= link_to "#{@stock.name}", stock_path(@stock) %></td>
    </tr>
  <% end %>
</tbody>
</table>
<br>
<br>


<%= link_to "Stock Page", stocks_path %>

app/views/holdings/most.html.erb
Stock: <%= Holding.most.stock.name %><br>
Holding: <%= Holding.most.balance %>

app/views/holdings/new.html.erb
<%= form_for @holding do |f| %>
    <%= f.hidden_field :stock_id %>
    Purchase Unit: <%= f.text_field :balance %><br>
    <br>
    <br>
    <%= submit_tag "Buy Stock" %>
   <% end %>

app/views/holdings/show.html.erb
<%= render 'accounts/alert' %>


<h4><%= "You are selling #{@stock.name} stocks" %></h4>
<p>Your purchase price: <%= @holding.price %></p>
<p>Your selling price: <%= @stock.price %></p>
<p>Your have: <%= @holding.balance %> stocks</p><br>

<%= form_for @holding do |f| %>
    <%= f.hidden_field :stock_id %>
    Sell: <%= text_field_tag :unit %> stocks<br>
    <br>
    <br>
    <%= f.submit "Sell Stock" %>
   <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>XChange</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/stocks/edit.html.erb
<%= form_for @stock do |f| %>
   Stock Name: <%= f.text_field :name %><br>
   Stock Price: <%= f.text_field :price %><br>
   <br>
   <br>
   <%= f.submit "Edit Stock" %>
   <% end %>

app/views/stocks/index.html.erb
<%= render 'accounts/alert' %>

<h3>Stock Selection</h3>

 <table class="table">
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

   <tbody>
    <tr>
      <td><strong>Stock Name </strong></td>
      <td><strong>Stock Price </strong></td>
      <td><strong>Stock Link </strong></td>
    </tr>
    <% @stocks.each do |s| %>
      <tr>

         <td><%= s.name %></td>
        <td><%= s.price %></td>
        <% if current_account.broker_acc %>
          <td><%= link_to "Show #{s.name}", stock_path(s) %></td>
        <% else %>
          <td><%= link_to "Buy #{s.name}", stock_path(s) %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

 <% if current_account %>
    <% if current_account.broker_acc %>
    <p>
    <%= link_to "Add New Stocks", new_stock_path %>
    </p>
    <% end %>
    <p>
    <%= link_to "Back to Account", account_path(current_account) %>
    </p>
<% end %>

app/views/stocks/new.html.erb
<%= form_for @stock do |f| %>
   Stock Name: <%= f.text_field :name %><br>
   Stock Price: <%= f.text_field :price %><br>
   <br>
   <br>
   <%= f.submit "Create Stock" %>
<% end %>

app/views/stocks/show.html.erb
<p>Stock Name: <%= @stock.name %></p>
<p>Stock Price: <%= @stock.price %></p>
<%= link_to "Buy Stock",  new_stock_holding_path(@stock) %>
<br>
<% if current_account.broker_acc %>
<%= link_to "Edit Stock", edit_stock_path %>
<%end%>
<br>
<%= link_to "Back to Stock Selection", stocks_path %>